# Generated by Django 2.0.2 on 2018-05-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180505_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='caller',
        ),
        migrations.RemoveField(
            model_name='products',
            name='dealName',
        ),
        migrations.AddField(
            model_name='products',
            name='broker',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='fundAmt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='funder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='lead',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='merchant',
            field=models.CharField(max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='note',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='tranDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
