# Generated by Django 2.0.2 on 2018-05-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180513_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='tranDate',
            field=models.DateTimeField(null=True),
        ),
    ]
