# Generated by Django 2.0.2 on 2018-10-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181021_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dealStatus',
            field=models.CharField(choices=[('CONTRACT REQUESTED', 'contract requested'), ('CONTRACT OUT', 'contract out'), ('SIGNED CONTRACT', 'signed contract'), ('FUNDED', 'funded')], default='CONTRACT REQUESTED', max_length=20),
        ),
    ]
